### ISSUE TITLE
1.74 branch fails to build with LLVM 19

### ISSUE THREAD

**Issue by theoparis** [thepowersgang/mrustc#337] opened 2024-11-24 02:38 UTC
```
   65 | ::std::ostream& operator<<(::std::ostream& os, const ::std::vector<T>& v)
      |                 ^
../common/debug.h:38:12: error: call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup
   38 |         os << v;
      |            ^
manifest.cpp:39:50: note: in instantiation of function template specialization '(anonymous namespace)::format_to_stream<std::vector<std::string>, const char *, TomlValue>' requested here
   39 |         do_fatal("error", [&](std::ostream& os){ format_to_stream(os, args...); });
      |                                                  ^
manifest.cpp:148:24: note: in instantiation of function template specialization 'ErrorHandler::error<std::vector<std::string>, const char *, TomlValue>' requested here
  148 |                     eh.error(key_val.path, ": Incorrect type ", key_val.value);
      |                        ^
../common/debug.h:65:17: note: 'operator<<' should be declared prior to the call site
   65 | ::std::ostream& operator<<(::std::ostream& os, const ::std::vector<T>& v)
      |            
```

**Comment by theoparis** [comment] 2024-11-24 02:39
Related #336

**Comment by thepowersgang** [comment] 2024-11-24 02:42
Duplicate of #336

**Closed by thepowersgang** 2024-11-24 02:42 UTC
