### ISSUE TITLE
Error running make -f minicargo.mk

### ISSUE THREAD

**Issue by thelearnerofcode** [thepowersgang/mrustc#41] opened 2017-12-24 13:32 UTC
- What I am trying to build:
make -f minicargo.mk
- Host System:
Fedora 27
- C/C++ compiler version:
gcc 7.2.1
- Mrustc Revision:
https://github.com/thepowersgang/mrustc/commit/40d9ac73f5a7312cdd3c7c20a671561d230a02d7

Here is the output: 
[tmp.txt](https://github.com/thepowersgang/mrustc/files/1584849/tmp.txt)

**Comment by thepowersgang** [comment] 2017-12-25 11:36
Looks like a compiler segfault :/ not good.

Could you run the command listed near the end of the output with valgrind/gdb? And maybe provide the last few lines of `output/rustc-build/librustc_const_eval.hir_dbg.txt`

**Comment by coder543** [comment] 2017-12-25 16:04
I encountered the same issue using Ubuntu under the WSL on Windows 10. I have attached the gdb output here. The backtrace is nearly 75,000 stack frames long.... something seems to be misbehaving.

[gdb.txt](https://github.com/thepowersgang/mrustc/files/1585985/gdb.txt)

**Comment by thepowersgang** [comment] 2017-12-26 00:43
Confirmed locally. Caused by an incorrect MIR optimisation infinite looping (and allocating each time), wasn't caught in testing before the announcement. A fix is being tested now

**Comment by thepowersgang** [comment] 2017-12-26 02:34
Fixed in 9e3ab4278fea40b9282c3c6e166020763fd7028d

**Closed** 2017-12-26 13:53 UTC
