### ISSUE TITLE
Error during compilation on Release Linux Mint 18.1 Serena 64-bit

### ISSUE THREAD

**Issue by Herrgrim0** [thepowersgang/mrustc#74] opened 2018-05-09 12:30 UTC
When i run this command : `make -f minicargo.mk`
I got this error : 
`output/libstd.hir.o.c:49611:9: error: ‘_ZRK$aLfn_1_$Rs__ZN3std9panicking9PanicInfo_$T0_as__ZN4core3ops5FnMut$aL$T1_$Rs__ZN3std9panicking9PanicInfo$aR$aRcall_mut’ undeclared here (not in a function)
  (void*)_ZRK$aLfn_1_$Rs__ZN3std9panicking9PanicInfo_$T0_as__ZN4core3ops5FnMut$aL$T1_$Rs__ZN3std9panicking9PanicInfo$aR$aRcall_mut`

My active rustup toolchain is : nightly-x86_64-unknown-linux-gnu (default)  rustc 1.27.0-nightly (8ff4b4206 2018-05-08)

My OS and kernel : Linux RomMint 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Thank you for your help

**Comment by thepowersgang** [comment] 2018-05-09 14:04
Hmm... works for me on both 17.3 and 18.3. What version of gcc do you have? and did you custom-download the rustc source to build (or did you use `make RUSTCSRC`?)

Other questions: What commit of mrustc are you building?

**Comment by Herrgrim0** [comment] 2018-05-09 16:03
I currently test this project : https://github.com/emosenkis/esp-rs that execute both command `make RUSTCSRC` and `make -f minicargo.mk`.
I use `gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010`.

this is the last commit i get when i run git log --oneline : ba9b4c4 Docs

**Comment by thepowersgang** [comment] 2018-05-11 00:14
It looks like that script attempts to check out and use bffed50, but appears to do so in a way that doesn't change the current commit (as reported by git).

Failure confirmed with the commit used by esp-rs, current head works. Maybe open an issue with the esp-rs project requesting an upgrade?

**Comment by thepowersgang** [comment] 2018-05-20 02:36
Closing as this isn't a mrustc issue, it's esp-rs pinning to a non-functional revision (which failed CI - see https://travis-ci.org/thepowersgang/mrustc/builds/303911135)

**Closed by thepowersgang** 2018-05-20 02:36 UTC
