### ISSUE TITLE
Error building 1.39.0 core (libc v0.2.62 src/unix/bsd/apple/mod.rs)

### ISSUE THREAD

**Issue by evanmiller** [thepowersgang/mrustc#202] opened 2021-12-28 14:12 UTC
This is using the latest HEAD code with a few patches taken from the PR section. The error did not appear with builds from a couple of weeks ago.

```
:info:build > ./bin/mrustc -Z print-cfgs
:info:build (0/17) BUILDING core v0.0.0
:info:build > ./bin/mrustc rustc-1.39.0-src/src/libcore/lib.rs -o output-1.39.0/libcore.rlib --crate-name core --crate-type rlib -C emit-depfile=output-1.39.0/libcore.rlib.d --crate-tag 0_0_0 -g --cfg debug_assertions -O -L output-1.39.0 --edition 2018
:info:build TTStream:0: warn:0:Unexpected attribute allow_internal_unstable on associated item
:info:build rustc-1.39.0-src/src/libcore/slice/mod.rs:67: note: From here
:info:build TTStream:0: warn:0:Unexpected attribute allow_internal_unstable on associated item
:info:build rustc-1.39.0-src/src/libcore/str/mod.rs:2173: note: From here
:info:build (1/17) BUILDING rustc_std_workspace_core from rustc-std-workspace-core v1.99.0
:info:build > ./bin/mrustc rustc-1.39.0-src/src/tools/rustc-std-workspace-core/lib.rs -o output-1.39.0/librustc_std_workspace_core-1_99_0.rlib --crate-name rustc_std_workspace_core --crate-type rlib -C emit-depfile=output-1.39.0/librustc_std_workspace_core-1_99_0.rlib.d --crate-tag 1_99_0 -g --cfg debug_assertions -O -L output-1.39.0 --edition 2018 --extern core=output-1.39.0/libcore.rlib
:info:build (2/17) BUILDING libc v0.2.62 with features [rustc-dep-of-std,align,rustc-std-workspace-core]
:info:build >./bin/mrustc rustc-1.39.0-src/vendor/libc/src/lib.rs -o output-1.39.0/liblibc-0_2_62_Hd.rlib --crate-name libc --crate-type rlib -C emit-depfile=output-1.39.0/liblibc-0_2_62_Hd.rlib.d --crate-tag 0_2_62_Hd -g --cfg debug_assertions -O -L output-1.39.0 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_thread_local --cfg feature="rustc-dep-of-std" --cfg feature="align" --cfg feature="rustc-std-workspace-core" --extern rustc_std_workspace_core=output-1.39.0/librustc_std_workspace_core-1_99_0.rlib
:info:build TTStream:0: warn:0:Use of #![no_core] with itself or #![no_std]
:info:build rustc-1.39.0-src/vendor/libc/src/lib.rs:29: note: From here
:info:build rustc-1.39.0-src/vendor/libc/src/unix/bsd/apple/mod.rs:497: error:0:Unexpected token TOK_PAREN_OPEN, expected TOK_PAREN_CLOSE
:info:build TTStream:0: note: From here
:info:build rustc-1.39.0-src/vendor/libc/src/unix/bsd/apple/mod.rs:497: note: From here
:info:build rustc-1.39.0-src/vendor/libc/src/unix/bsd/apple/mod.rs:496: note: From here
:info:build Process was terminated with signal 6
:info:build FAILING COMMAND: ./bin/mrustc rustc-1.39.0-src/vendor/libc/src/lib.rs -o output-1.39.0/liblibc-0_2_62_Hd.rlib --crate-name libc --crate-type rlib -C emit-depfile=output-1.39.0/liblibc-0_2_62_Hd.rlib.d --crate-tag 0_2_62_Hd -g --cfg debug_assertions -O -L output-1.39.0 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_thread_local --cfg feature="rustc-dep-of-std" --cfg feature="align" --cfg feature="rustc-std-workspace-core" --extern rustc_std_workspace_core=output-1.39.0/librustc_std_workspace_core-1_99_0.rlib make: *** [output-1.39.0/libstd.rlib] Segmentation fault
:info:build Command failed: /usr/bin/env CXX=/opt/local/bin/clang++-mp-9.0 CC=/opt/local/bin/clang-mp-9.0 CXXFLAGS_EXTRA='-Os -stdlib=libc++' RUSTC_VERSION=1.39.0 MRUSTC_TARGET_VER=1.39 /usr/bin/make -f minicargo.mk LIBS
```

**Comment by thepowersgang** [comment] 2021-12-29 01:37
Caused by a refactor to handling of attributes, they're now a lot more picky about formatting (beforehand the `(4)` argument to `packed` would have been ignored)

**Comment by thepowersgang** [comment] 2021-12-30 06:48
Fixed in above commit (implemented parsing and utilisation of `#[repr(packed(N))]`)

**Closed** 2021-12-30 06:47 UTC
