### ISSUE TITLE
"Cannot satisfy dependencies" in run_rustc with rustc-1.29.0

### ISSUE THREAD

**Issue by r-burns** [thepowersgang/mrustc#187] opened 2021-09-01 00:46 UTC
I'm testing full rustc bootstrapping (using rustc version 1.29.0) with the new fixes for Linux/GCC (thanks!) and running into some issues during the run_rustc step. Crates are failing with e.g. ``error: cannot satisfy dependencies so `std` only shows up once``.

Notably, reverting commit b9b23c5184940123087167960d7cb75a38760003 fixes the issue, so I assume it's simply some discrepancy between the rustc 1.29.0 and 1.39.0 bootstrapping logic.

Relevant log portion:

<details>

```
make: Entering directory '/build/source/run_rustc'
cp ../output/rustc output/prefix-s/bin/rustc
[RUSTC] -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore.rlib
33.12user 0.26system 0:32.80elapsed 101%CPU (0avgtext+0avgdata 716668maxresident)k
6636inputs+100281outputs (13672major+181967minor)pagefaults 0swaps
[RUSTC] -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins.rlib
1.83user 0.03system 0:01.74elapsed 107%CPU (0avgtext+0avgdata 80212maxresident)k
580inputs+3082outputs (3128major+10186minor)pagefaults 0swaps
[RUSTC] -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc.rlib
0.90user 0.02system 0:00.91elapsed 101%CPU (0avgtext+0avgdata 90912maxresident)k
2010inputs+4182outputs (384major+13506minor)pagefaults 0swaps
[RUSTC] -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind.rlib
0.05user 0.00system 0:00.06elapsed 100%CPU (0avgtext+0avgdata 49228maxresident)k
63inputs+101outputs (135major+3404minor)pagefaults 0swaps
[RUSTC] -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system.rlib
0.05user 0.00system 0:00.05elapsed 110%CPU (0avgtext+0avgdata 51428maxresident)k
114inputs+126outputs (35major+3901minor)pagefaults 0swaps
[RUSTC] -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc.rlib
5.06user 0.05system 0:05.00elapsed 102%CPU (0avgtext+0avgdata 145260maxresident)k
1991inputs+12412outputs (929major+27293minor)pagefaults 0swaps
[RUSTC] -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind.rlib
0.15user 0.01system 0:00.13elapsed 118%CPU (0avgtext+0avgdata 63372maxresident)k
302inputs+524outputs (508major+5415minor)pagefaults 0swaps
[RUSTC] -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd.rlib
8.19user 0.08system 0:07.14elapsed 115%CPU (0avgtext+0avgdata 264508maxresident)k
5972inputs+37556outputs (2645major+57485minor)pagefaults 0swaps
0.13user 0.05system 0:00.17elapsed 103%CPU (0avgtext+0avgdata 59476maxresident)k
120161inputs+1308outputs (693major+17969minor)pagefaults 0swaps
cp ../output/rustc output/prefix/bin/rustc_m
cp ../output/cargo output/prefix/bin/cargo
[create] output/prefix/cargo_home/config
[CARGO] ../rustc-1.29.0-src/src/rustc/Cargo.toml > output/build-rustc
   Compiling nodrop v0.1.12
   Compiling cfg-if v0.1.4
   Compiling lazy_static v1.0.2
   Compiling void v1.0.2
   Compiling memoffset v0.2.1
   Compiling scopeguard v0.3.3
   Compiling libc v0.2.42
   Compiling rustc-rayon-core v0.1.1
   Compiling stable_deref_trait v1.1.0
   Compiling bitflags v1.0.3
   Compiling byteorder v1.2.3
   Compiling either v1.5.0
   Compiling serialize v0.0.0 (file:///build/source/rustc-1.29.0-src/src/libserialize)
   Compiling cc v1.0.18
   Compiling unicode-width v0.1.5
   Compiling rustc_target v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc_target)
   Compiling scoped-tls v0.1.2
   Compiling syntax v0.0.0 (file:///build/source/rustc-1.29.0-src/src/libsyntax)
   Compiling termcolor v0.3.6
   Compiling lazy_static v0.2.11
   Compiling datafrog v0.1.0
   Compiling remove_dir_all v0.5.1
   Compiling rustc v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc)
   Compiling rustc-demangle v0.1.8
   Compiling build_helper v0.1.0 (file:///build/source/rustc-1.29.0-src/src/build_helper)
   Compiling graphviz v0.0.0 (file:///build/source/rustc-1.29.0-src/src/libgraphviz)
   Compiling rustc_incremental v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc_incremental)
   Compiling fmt_macros v0.0.0 (file:///build/source/rustc-1.29.0-src/src/libfmt_macros)
   Compiling rustc-serialize v0.3.24
   Compiling rustc_metadata v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc_metadata)
   Compiling quick-error v1.2.2
   Compiling rustc_codegen_llvm v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc_codegen_llvm)
   Compiling rustc_platform_intrinsics v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc_platform_intrinsics)
   Compiling rustc_driver v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc_driver)
   Compiling arrayvec v0.4.7
   Compiling crossbeam-utils v0.2.2
   Compiling log v0.4.3
   Compiling log_settings v0.1.2
   Compiling unreachable v1.0.0
   Compiling rand v0.4.2
   Compiling num_cpus v1.8.0
   Compiling atty v0.2.11
   Compiling owning_ref v0.3.3
   Compiling rustc-hash v1.0.1
   Compiling miniz-sys v0.1.10
   Compiling backtrace-sys v0.1.24
   Compiling chalk-macros v0.1.0
   Compiling rustc_llvm v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc_llvm)
   Compiling rls-span v0.4.0
   Compiling humantime v1.1.1
   Compiling crossbeam-epoch v0.3.1
   Compiling ena v0.9.3
   Compiling rustc_cratesio_shim v0.0.0 (file:///build/source/rustc-1.29.0-src/src/librustc_cratesio_shim)
   Compiling jobserver v0.1.11
   Compiling smallvec v0.6.3
   Compiling tempfile v3.0.2
   Compiling polonius-engine v0.5.0
   Compiling chalk-engine v0.6.0
warning: ../rustllvm/PassWrapper.cpp: In lambda function:
warning: ../rustllvm/PassWrapper.cpp:1095:23: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
warning:  1095 |       return std::move(MOrErr);
warning:       |              ~~~~~~~~~^~~~~~~~
warning: ../rustllvm/PassWrapper.cpp:1095:23: note: remove 'std::move' call
warning: ../rustllvm/PassWrapper.cpp:1113:23: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
warning:  1113 |       return std::move(Ret);
warning:       |              ~~~~~~~~~^~~~~
warning: ../rustllvm/PassWrapper.cpp:1113:23: note: remove 'std::move' call
warning: ../rustllvm/PassWrapper.cpp:1120:21: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
warning:  1120 |     return std::move(MOrErr);
warning:       |            ~~~~~~~~~^~~~~~~~
warning: ../rustllvm/PassWrapper.cpp:1120:21: note: remove 'std::move' call
   Compiling rls-data v0.16.0
   Compiling env_logger v0.5.10
   Compiling crossbeam-deque v0.2.0
error: cannot satisfy dependencies so `std` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `core` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `compiler_builtins` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `alloc` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `alloc_system` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `libc` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `unwind` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `panic_unwind` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: Could not compile `rustc_target`.

To learn more, run the command again with --verbose.
make: *** [Makefile:139: output/prefix/bin/rustc] Error 101
```

</details>

**Comment by r-burns** [comment] 2021-09-02 01:53
cc @progval re: https://github.com/NixOS/nixpkgs/pull/113817#issuecomment-813310730

**Comment by thepowersgang** [comment] 2021-12-30 07:20
Finally got around to confirming this, might be a codegen error somewhere.

**Comment by thepowersgang** [comment] 2021-12-31 05:42
Or, it's a config/environment error (as you imply by that commit). Not sure what the cause could be.

**Comment by thepowersgang** [comment] 2021-12-31 09:13
Likely cause: Dynamic linking of some of the rustc crates leads to multiple copies of `std` (because std isn't compiled as a dylib)

**Comment by thepowersgang** [comment] 2022-01-01 12:00
Should be fixed with the above commit

**Comment by r-burns** [comment] 2022-01-02 11:04
Hmm, I'm testing on 931ee7c1d0ac2df70caa2b471bfe9eef9643bed1 (with https://github.com/thepowersgang/mrustc/pull/206) but now running into another std-related error during run_rustc:

```
(2/3) BUILDING test v0.0.0
> /nix/store/8iai5p0xbbp6najx966dhhgk8y14fdq0-mrustc-unstable-20210830/bin/mrustc ../rustc-1.29.0-src/src/libtest/lib.rs -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest.rlib --crate-name test --crate-type rlib -C emit-depfile=output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest.rlib.d --crate-tag 0_0_0 -g --cfg debug_assertions -O -L output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib --extern getopts=output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-0_2_17.rlib --extern term=output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm.rlib
error[E0463]: can't find crate for `std`

make: *** [Makefile:128: output/prefix-s/bin/hello_world] Aborted (core dumped)
```

**Comment by thepowersgang** [comment] 2022-01-02 11:11
That looks like it's calling `mrust` not `rustc`

**Comment by r-burns** [comment] 2022-01-02 23:39
Hmm, I think you are right but I'm not sure why this is happening, the MRUSTC_PATH is correct for the rustc_m/minicargo stage as far as I can tell. Here's a longer snippet showing the minicargo invocation (happy to provide the full log if that would be more helpful):
 
<details>

```
MRUSTC_PATH=/build/source/run_rustc/output/prefix-s/bin/rustc /nix/store/x1vg0gyg10i0y160vmzvbp7im888m3hd-mrustc-minicargo-unstable-20210830/bin/minicargo --vendor-dir ../rustc-1.29.0-src/src/vendor --script-overrides ../script-overrides/stable-1.29.0-linux/ --output-dir output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/ ../rustc-1.29.0-src/src/libtest
> /nix/store/8iai5p0xbbp6najx966dhhgk8y14fdq0-mrustc-unstable-20210830/bin/mrustc -Z print-cfgs
(0/3) BUILDING term v0.0.0
> /nix/store/8iai5p0xbbp6najx966dhhgk8y14fdq0-mrustc-unstable-20210830/bin/mrustc ../rustc-1.29.0-src/src/libterm/lib.rs -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm.rlib --crate-name term --crate-type rlib -C emit-depfile=output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm.rlib.d --crate-tag 0_0_0 -g --cfg debug_assertions -O -L output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib
(1/3) BUILDING getopts v0.2.17
> /nix/store/8iai5p0xbbp6najx966dhhgk8y14fdq0-mrustc-unstable-20210830/bin/mrustc ../rustc-1.29.0-src/src/vendor/getopts/src/lib.rs -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-0_2_17.rlib --crate-name getopts --crate-type rlib -C emit-depfile=output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-0_2_17.rlib.d --crate-tag 0_2_17 -g --cfg debug_assertions -O -L output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib
(2/3) BUILDING test v0.0.0
> /nix/store/8iai5p0xbbp6najx966dhhgk8y14fdq0-mrustc-unstable-20210830/bin/mrustc ../rustc-1.29.0-src/src/libtest/lib.rs -o output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest.rlib --crate-name test --crate-type rlib -C emit-depfile=output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest.rlib.d --crate-tag 0_0_0 -g --cfg debug_assertions -O -L output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib --extern getopts=output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-0_2_17.rlib --extern term=output/prefix-s/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm.rlib
[CARGO] ../rustc-1.29.0-src/src/libtest/Cargo.toml > output/build-std2
   Compiling cc v1.0.18
   Compiling core v0.0.0 (file:///build/source/rustc-1.29.0-src/src/libcore)
   Compiling unwind v0.0.0 (file:///build/source/rustc-1.29.0-src/src/libunwind)
   Compiling build_helper v0.1.0 (file:///build/source/rustc-1.29.0-src/src/build_helper)
error[E0463]: can't find crate for `std`
error[E0463]: can't find crate for `std`


error[E0463]: can't find crate for `std`

Aborted (core dumped)
error: Could not compile `unwind`.
warning: build failed, waiting for other jobs to finish...
Aborted (core dumped)
error: Could not compile `build_helper`.
warning: build failed, waiting for other jobs to finish...
Aborted (core dumped)
error: Could not compile `cc`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:138: output/prefix-2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest.rlib] Error 101
make: Leaving directory '/build/source/run_rustc'
```

</details>

**Comment by thepowersgang** [comment] 2022-01-03 02:49
I see you're using an out-of-tree `minicargo`
Is it possible that the `minicargo` build is old enough that it doesn't have that feature?

**Comment by r-burns** [comment] 2022-01-03 02:57
Ignore the `unstable-20210830` in the install prefix - I've been building everything off the same commit (here https://github.com/thepowersgang/mrustc/commit/931ee7c1d0ac2df70caa2b471bfe9eef9643bed1), including that minicargo, it's just installed to the system as a separate package.

**Comment by thepowersgang** [comment] 2022-01-03 02:59
Well, something is going very wrong - because it's definitely using the sysroot mrustc over the environemnt variable version. I don't think I can reproduce this (easily), so you'll have to do some digging into why the environment variable isn't being used.

**Comment by r-burns** [comment] 2022-01-03 03:39
Much appreciated, I'll keep digging into it. If you don't mind installing Nix, reproducing should be as simple as checking out https://github.com/r-burns/nixpkgs/commit/7cb86b7b9321381e9b7ef9648fc3d5bdfae6b620 and running `nix-build . -A mrustc-bootstrap`.

**Comment by thepowersgang** [comment] 2022-01-03 03:40
I have bigger bugs to fix currently (bootstrap is completely broken due to symbol hash issues)

**Comment by thepowersgang** [comment] 2022-01-04 12:44
Bootstrap checked with both 1.29 and 1.39. Closing issue

**Closed by thepowersgang** 2022-01-04 12:44 UTC
